### ISSUE TITLE
process.env.PORT for cloud services

### ISSUE THREAD

**Issue by Kikobeats** [soyjavi/zen-server#3]
Hello!

You know that some cloud hosting services provide the port for your web application by `process.env.port` environment variable. At this moment I think that is not supported yet (I'm trying to deploy in heroku...)

So, what is the state of this? I suppose that the line that must change is [this](https://github.com/soyjavi/zen-server/blob/master/lib/zen.config.coffee#L22) :-)

**Comment by Kikobeats** [comment]
GOTO #4

**Comment by soyjavi** [comment]
Accepted and closed :100:
