### ISSUE TITLE
Working with Socket.io

### ISSUE THREAD

**Issue by hu9osaez** [soyjavi/zen-server#8]
Hello Javi,

I've been looking a bit like zen-server works and the truth I could not make it work in conjunction with Socket.io, as this generates an enormous log when running and then the server stops running. In simple words, doesn't work.

Is there any easy way to bring this to fruition without fail?

I would not want to use expressjs having the simplicity of zen-server.

Stay tuned.

Cheers :)

**Comment by hasaezs** [comment]
After giving several laps I managed to make it work.
I think now if it lacks nothing to zenserver :smile:
